/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const OrderProduct = IDL.Record({
  'productId' : IDL.Nat,
  'variantId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentStatus' : IDL.Opt(IDL.Text),
  'paymentMethod' : IDL.Opt(IDL.Text),
  'transactionReference' : IDL.Opt(IDL.Text),
  'orderDate' : Time,
  'totalAmount' : IDL.Float64,
  'customerId' : IDL.Nat,
  'isNew' : IDL.Bool,
  'discountedAmount' : IDL.Opt(IDL.Float64),
  'products' : IDL.Vec(OrderProduct),
  'promoCodeId' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'inStock' : IDL.Bool,
  'healthBenefits' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const PromoCode = IDL.Record({
  'id' : IDL.Nat,
  'expiryDate' : IDL.Opt(Time),
  'code' : IDL.Text,
  'discountType' : IDL.Variant({
    'flat' : IDL.Float64,
    'percentage' : IDL.Float64,
  }),
  'minOrderValue' : IDL.Float64,
  'isActive' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'mobile' : IDL.Opt(IDL.Text),
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const ProductVariant = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'productId' : IDL.Nat,
  'isActive' : IDL.Bool,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'createPromoCode' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({ 'flat' : IDL.Float64, 'percentage' : IDL.Float64 }),
        IDL.Float64,
        IDL.Opt(Time),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'createVariant' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Bool, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deletePromoCode' : IDL.Func([IDL.Nat], [], []),
  'deleteVariant' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
  'getCallerOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomerByMobile' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getNewOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getOrdersByCustomer' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVariant' : IDL.Func([IDL.Nat], [IDL.Opt(ProductVariant)], ['query']),
  'getVariantsByProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductVariant)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOrderAsSeen' : IDL.Func([IDL.Nat], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Nat, IDL.Vec(OrderProduct), IDL.Float64, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updatePromoCode' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Variant({ 'flat' : IDL.Float64, 'percentage' : IDL.Float64 }),
        IDL.Float64,
        IDL.Opt(Time),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateVariant' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'validatePromoCode' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [IDL.Opt(PromoCode)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const OrderProduct = IDL.Record({
    'productId' : IDL.Nat,
    'variantId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentStatus' : IDL.Opt(IDL.Text),
    'paymentMethod' : IDL.Opt(IDL.Text),
    'transactionReference' : IDL.Opt(IDL.Text),
    'orderDate' : Time,
    'totalAmount' : IDL.Float64,
    'customerId' : IDL.Nat,
    'isNew' : IDL.Bool,
    'discountedAmount' : IDL.Opt(IDL.Float64),
    'products' : IDL.Vec(OrderProduct),
    'promoCodeId' : IDL.Opt(IDL.Nat),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'inStock' : IDL.Bool,
    'healthBenefits' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const PromoCode = IDL.Record({
    'id' : IDL.Nat,
    'expiryDate' : IDL.Opt(Time),
    'code' : IDL.Text,
    'discountType' : IDL.Variant({
      'flat' : IDL.Float64,
      'percentage' : IDL.Float64,
    }),
    'minOrderValue' : IDL.Float64,
    'isActive' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'mobile' : IDL.Opt(IDL.Text),
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const ProductVariant = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'productId' : IDL.Nat,
    'isActive' : IDL.Bool,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'createPromoCode' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({ 'flat' : IDL.Float64, 'percentage' : IDL.Float64 }),
          IDL.Float64,
          IDL.Opt(Time),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'createVariant' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Bool, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deletePromoCode' : IDL.Func([IDL.Nat], [], []),
    'deleteVariant' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
    'getCallerOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomerByMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Customer)],
        ['query'],
      ),
    'getNewOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getOrdersByCustomer' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVariant' : IDL.Func([IDL.Nat], [IDL.Opt(ProductVariant)], ['query']),
    'getVariantsByProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductVariant)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOrderAsSeen' : IDL.Func([IDL.Nat], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Nat, IDL.Vec(OrderProduct), IDL.Float64, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updatePromoCode' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Variant({ 'flat' : IDL.Float64, 'percentage' : IDL.Float64 }),
          IDL.Float64,
          IDL.Opt(Time),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateVariant' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'validatePromoCode' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [IDL.Opt(PromoCode)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };