/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
}
export interface Customer {
  'id' : bigint,
  'name' : string,
  'address' : string,
  'mobile' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentStatus' : [] | [string],
  'paymentMethod' : [] | [string],
  'transactionReference' : [] | [string],
  'orderDate' : Time,
  'totalAmount' : number,
  'customerId' : bigint,
  'isNew' : boolean,
  'discountedAmount' : [] | [number],
  'products' : Array<OrderProduct>,
  'promoCodeId' : [] | [bigint],
}
export interface OrderProduct {
  'productId' : bigint,
  'variantId' : bigint,
  'quantity' : bigint,
  'price' : number,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null };
export interface Product {
  'id' : bigint,
  'categoryId' : bigint,
  'inStock' : boolean,
  'healthBenefits' : string,
  'name' : string,
  'description' : string,
  'images' : Array<ExternalBlob>,
}
export interface ProductVariant {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'productId' : bigint,
  'isActive' : boolean,
  'price' : number,
}
export interface PromoCode {
  'id' : bigint,
  'expiryDate' : [] | [Time],
  'code' : string,
  'discountType' : { 'flat' : number } |
    { 'percentage' : number },
  'minOrderValue' : number,
  'isActive' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'address' : [] | [string],
  'mobile' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string, [] | [ExternalBlob]], bigint>,
  'createCustomer' : ActorMethod<[string, string, string], bigint>,
  'createProduct' : ActorMethod<
    [string, bigint, string, string, Array<ExternalBlob>, boolean],
    bigint
  >,
  'createPromoCode' : ActorMethod<
    [
      string,
      { 'flat' : number } |
        { 'percentage' : number },
      number,
      [] | [Time],
      boolean,
    ],
    bigint
  >,
  'createVariant' : ActorMethod<
    [bigint, string, number, boolean, boolean],
    bigint
  >,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deletePromoCode' : ActorMethod<[bigint], undefined>,
  'deleteVariant' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllPromoCodes' : ActorMethod<[], Array<PromoCode>>,
  'getCallerOrderHistory' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomerByMobile' : ActorMethod<[string], [] | [Customer]>,
  'getNewOrderCount' : ActorMethod<[], bigint>,
  'getOrdersByCustomer' : ActorMethod<[bigint], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[bigint], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVariant' : ActorMethod<[bigint], [] | [ProductVariant]>,
  'getVariantsByProduct' : ActorMethod<[bigint], Array<ProductVariant>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOrderAsSeen' : ActorMethod<[bigint], undefined>,
  'placeOrder' : ActorMethod<
    [bigint, Array<OrderProduct>, number, [] | [bigint]],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<
    [bigint, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, bigint, string, string, Array<ExternalBlob>, boolean],
    undefined
  >,
  'updatePromoCode' : ActorMethod<
    [
      bigint,
      string,
      { 'flat' : number } |
        { 'percentage' : number },
      number,
      [] | [Time],
      boolean,
    ],
    undefined
  >,
  'updateVariant' : ActorMethod<
    [bigint, bigint, string, number, boolean, boolean],
    undefined
  >,
  'validatePromoCode' : ActorMethod<[string, number], [] | [PromoCode]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];